name: "jakubojo"
description: ""
url: "www.jakubojo.com"
tagline: jakubojo LLC provides exceptional consulting services including software development, systems analysis, and business intelligence.
timezone: UTC
permalink: pretty
gems:
  - jekyll-feed
  - jekyll-sitemap
exclude: [bower_components, node_modules, bower.json, package.json, Gruntfile.js]