name: "jakubojo"
description: ""
url: "www.jakubojo.com"
tagline: jakubojo LLC provides exceptional consulting services including software development, systems analysis, and business intelligence.
timezone: UTC
gems:
  - jekyll-feed
  - jekyll-sitemap
